version: "3"
services:
  web:
    build: ./webapp
    ports:
      - "5000:5000"
    volumes:
      - ./webapp:/code

  scrapy:
    build: .

  mongo:
    image: mongo:3.6
    ports:
      - "27017:27017"
    volumes:
      - /home/liurui/data/db:/data/db
      - /home/liurui/data/configdb:/data/configdb
